# Nowa aplikacja Shopify - Asystent EPIR v2
# Po utworzeniu aplikacji w Partners, wklej tutaj nowy client_id i zaktualizuj redirect_urls

client_id = "74ac36ea2ce7f727f5ef7874a9b1697f"
name = "Asystent-EPIR-Jewellery"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "read_products,read_customers,read_orders"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/api/auth"
]

[app_proxy]
url = "https://epir-art-jewellery-worker.krzysztofdzugaj.workers.dev"
subpath = "assistant"
prefix = "apps"
